Repository unanchoi/KeyGo-server, pull requests merged in 2023-05, with the labels that each got.

#56 [FEAT] appleLogin API 구현
  build.gradle
  src/main/java/maddori/keygo/common/exception/GlobalExceptionHandler.java
  src/main/java/maddori/keygo/common/response/ResponseCode.java
  src/main/java/maddori/keygo/common/util/JwtHandler.java
  src/main/java/maddori/keygo/controller/AuthController.java
  src/main/java/maddori/keygo/domain/entity/User.java
  src/main/java/maddori/keygo/dto/auth/LoginRequestDto.java
  src/main/java/maddori/keygo/dto/auth/LoginResponseDto.java
  src/main/java/maddori/keygo/repository/UserRepository.java
  src/main/java/maddori/keygo/service/AuthService.java
  src/main/resources/application-config.yml
Labels: 🛠️ feat

#59 [FEAT] S3 이미지 업로드 구현
  build.gradle
  src/main/java/maddori/keygo/common/util/ImageHandler.java
  src/main/java/maddori/keygo/config/S3Config.java
  src/main/java/maddori/keygo/service/TeamService.java
  src/main/java/maddori/keygo/service/UserService.java
  src/main/resources/application.yml
Labels: 🛠️ feat

#62 [REFACTOR] 피드백 생성 API 수정
  .github/workflows/pr-build.yml
  .gitignore
  src/main/java/maddori/keygo/config/S3Config.java
  src/main/java/maddori/keygo/config/TimezoneConfig.java
  src/main/java/maddori/keygo/controller/FeedbackController.java
  src/main/java/maddori/keygo/service/FeedbackService.java
  src/main/resources/application.yml
Labels: enhancement

#63 [FEAT] 유저 인증 로직 구현 및 적용
  src/main/java/maddori/keygo/common/exception/GlobalExceptionHandler.java
  src/main/java/maddori/keygo/config/AppConfig.java
  src/main/java/maddori/keygo/config/S3Config.java
  src/main/java/maddori/keygo/config/WebMvcConfig.java
  src/main/java/maddori/keygo/controller/AuthController.java
  src/main/java/maddori/keygo/controller/FeedbackController.java
  src/main/java/maddori/keygo/controller/TeamController.java
  src/main/java/maddori/keygo/controller/UserController.java
  src/main/java/maddori/keygo/security/JwtAuthenticationInterceptor.java
  src/main/java/maddori/keygo/security/JwtAuthenticationToken.java
  src/main/java/maddori/keygo/security/JwtHandler.java
  src/main/java/maddori/keygo/security/SecurityService.java
  src/main/java/maddori/keygo/service/AuthService.java
Labels: 🛠️ feat

#65 [FEAT] application-config.yml에서 환경 변수 값 가져올 수 있도록 수정
  .gitignore
  src/main/java/maddori/keygo/security/JwtHandler.java
  src/main/resources/application.yml
Labels: ✨ feat

#67 [CHORE] reflection date 'yyyy-MM-dd HH:mm:ss' 형식으로 통일
  src/main/java/maddori/keygo/dto/reflection/ReflectionCurrentResponseDto.java
  src/main/java/maddori/keygo/dto/reflection/ReflectionResponseDto.java
  src/main/java/maddori/keygo/dto/reflection/ReflectionUpdateRequestDto.java
  src/main/java/maddori/keygo/dto/reflection/ReflectionUpdateResponseDto.java
  src/main/java/maddori/keygo/service/ReflectionService.java
Labels: 🛠 chore

#69 [FEAT] 프로필 수정(editProfile) API 구현
  src/main/java/maddori/keygo/controller/UserController.java
  src/main/java/maddori/keygo/domain/entity/UserTeam.java
  src/main/java/maddori/keygo/service/UserService.java
Labels: ✨ feat

#74 [FEAT] getFromMeToMemberFeedbackList API 구현
  src/main/java/maddori/keygo/controller/FeedbackController.java
  src/main/java/maddori/keygo/controller/ReflectionController.java
  src/main/java/maddori/keygo/dto/feedback/FeedbackContentResponseDto.java
  src/main/java/maddori/keygo/dto/feedback/FeedbackFromMeToMemberResponseDto.java
  src/main/java/maddori/keygo/service/FeedbackService.java
Labels: ✨ feat

#78 [HOTFIX] API 버그 수정
  src/main/java/maddori/keygo/common/response/ResponseCode.java
  src/main/java/maddori/keygo/common/response/SuccessResponse.java
  src/main/java/maddori/keygo/controller/FeedbackController.java
  src/main/java/maddori/keygo/controller/ReflectionController.java
  src/main/java/maddori/keygo/service/FeedbackService.java
  src/main/java/maddori/keygo/service/ReflectionService.java
  src/main/java/maddori/keygo/service/ReflectionStateValidator.java
  src/main/java/maddori/keygo/service/ReflectionValidationService.java
Labels: 🐞 bug

#80 [HOTFIX] api test bug 수정
  src/main/java/maddori/keygo/controller/ReflectionController.java
  src/main/java/maddori/keygo/service/AuthService.java
  src/main/java/maddori/keygo/service/FeedbackService.java
  src/main/java/maddori/keygo/service/ReflectionValidationService.java
Labels: 🐞 bug

#82 [HOTFIX] 각종 버그 수정 및 코드 보완
  src/main/java/maddori/keygo/repository/FeedbackRepository.java
  src/main/java/maddori/keygo/service/FeedbackService.java
  src/main/java/maddori/keygo/service/ReflectionService.java
  src/main/java/maddori/keygo/service/TeamService.java
  src/main/java/maddori/keygo/service/UserService.java
Labels: 🐞 bug, 🛠 chore
